jobs:
  execute-notebook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: { python-version: '3.11' }
      - run: pip install jupyter nbconvert
      - name: Execute notebook
        run: |
          jupyter nbconvert --to notebook --execute --inplace \
            2_semestr/lr_9/data/лаба_9.ipynb
      - uses: actions/upload-artifact@v3
        with:
          name: executed-notebook
          path: 2_semestr/lr_9/data/лаба_9.ipynb

  build-and-publish-docs:
    needs: execute-notebook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: { python-version: '3.11' }
      - uses: actions/download-artifact@v3
        with:
          name: executed-notebook
          path: ./src/docs/notebooks/   # чтобы MkDocs увидел
      - run: pip install mkdocs
      - run: |
          mkdocs build -f ./src/mkdocs.yml -d ../docs
      - name: Publish to release
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "<>"
          git fetch origin release || true
          git checkout -B release origin/release || git checkout -b release
          git add ./docs
          git commit -m "feat: обновление сайта" || echo "No changes"
          git push origin release -f